### ISSUE TITLE
Weird color on status line

### ISSUE THREAD

**Issue by tin-pham** [shaeinst/roshnivim-cs#1]
![image](https://user-images.githubusercontent.com/20679090/146539935-b45d191f-0f96-4443-8902-46d25b323797.png)

**Comment by shaeinst** [comment]
What do you mean?
> Weird color on status line 

btw, i have changed the status line default color with black(#141414).

**Comment by tin-pham** [comment]
Thanks, great theme 
![image](https://user-images.githubusercontent.com/20679090/146619321-4abffaa1-673b-47a4-a44b-dd827284598d.png)
